### ISSUE TITLE
master branch is broken / please make a new release?

### ISSUE THREAD

**Issue by bastelfreak** [deanwilson/puppet-lint-no_erb_template-check#42]
Hi!
another plugin I would like to use :)
I noticed that the following code isn't detected as bad with your latest release:

```puppet
  file { "/etc/${package_name}.conf":
    ensure  => file,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template("allknowingdns/${package_name}.conf.erb"),
    notify  => Service[$package_name],
    require => Package[$package_name],
  }
```

But your master branch detects it properly. Given that the last release is quite old, could you please do a 1.0.0 release?

**Comment by deanwilson** [comment]
A new release has been tagged and pushed to [RubyGems](https://rubygems.org/gems/puppet-lint-no_erb_template-check/versions/1.0.0). Thank you for flagigng this and I hope the plugin is useful
